services:
  - type: web
    name: proyecto-ti
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
